Cv:
    path: /cv
    controller: App\Controller\CvController::index

Inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

index:
    path: /
    controller: App\Controller\AccueilController::index

Evenement :
    path: /evenement
    controller: App\Controller\EvenementController::index