Competence:
    path: /cv/competence
    controller: App\Controller\CvController::indexCompetence

Cv:
    path: /cv
    controller: App\Controller\CvController::indexCv

Inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

index:
    path: /
    controller: App\Controller\AccueilController::index
